Args: --style=examples/style/udnie.jpg --train_dir=$RUNDIR --test=examples/content/chicago.jpg
  --test-dir=/training/tests --content-weight=1.5e1 --checkpoint-iterations=1000 --batch-size=10
  --train-path=/workspace/data/train2014 --vgg-path=/workspace/data/imagenet-vgg-verydeep-19.mat
  --epochs=3 --style-weight=200 --limit_train=2000
Cmd: style.py
EnvVars: []
ExecutionDir: /src/fast-style-transfer
Images:
  BaseImage: tensorflow/tensorflow
  GpuImage: tensorflow/tensorflow:latest-gpu
  PSImage: tensorflow/tensorflow
Jupyter:
  UseGPU: false
MonitoringNamespace: kuberlab
PythonPackages:
  - pillow
  - scipy
Requests:
  CPU: 100m
  CPULimit: 8000m
  GPU: 1
  Memory: 2Gi
  MemoryLimit: 64Gi
  PsPods: 1
  WorkerPods: 1
Volumes:
- isLibDir: false
  isTrainLogDir: true
  mountPath: /training
  name: training
  clusterStorage: {{ .storage }}
  subPath: training
- gitRepo:
    repository: https://github.com/dreyk/fast-style-transfer
  isLibDir: false
  isTrainLogDir: false
  mountPath: /src
  name: src
  subPath: ""
- isLibDir: true
  isTrainLogDir: false
  mountPath: /workspace/lib
  name: lib
  clusterStorage: {{ .storage }}
  subPath: lib
- hostPath:
    path: /fast-data
  isLibDir: false
  isTrainLogDir: false
  mountPath: /workspace/data
  name: data
  subPath: ""
- isLibDir: false
  isTrainLogDir: false
  mountPath: /test
  name: test
  clusterStorage: {{ .storage }}
  subPath: test
